"""empty message

Revision ID: 1c92cb790413
Revises: c4f94eec820
Create Date: 2015-09-14 13:21:00.862523

"""

# revision identifiers, used by Alembic.
revision = '1c92cb790413'
down_revision = 'c4f94eec820'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('body', sa.String(length=999), nullable=True))
    op.create_index(op.f('ix_question_body'), 'question', ['body'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_body'), table_name='question')
    op.drop_column('question', 'body')
    ### end Alembic commands ###
