"""empty message

Revision ID: 676652d96b3
Revises: 3a208da5cbf5
Create Date: 2015-09-14 19:17:10.445000

"""

# revision identifiers, used by Alembic.
revision = '676652d96b3'
down_revision = '3a208da5cbf5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    ### end Alembic commands ###
